steps:
    - name: 'gcr.io/cloud-builders/docker'
      args:
          - build
          - -t
          - us-central1-docker.pkg.dev/$PROJECT_ID/tarot-api-container/tarot-api:$COMMIT_SHA
          - .

    - name: 'gcr.io/cloud-builders/docker'
      args:
          - push
          - us-central1-docker.pkg.dev/$PROJECT_ID/tarot-api-container/tarot-api:$COMMIT_SHA

    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args:
          - run
          - deploy
          - tarot-api
          - --image=us-central1-docker.pkg.dev/$PROJECT_ID/tarot-api-container/tarot-api:$COMMIT_SHA
          - --region=us-central1
          - --platform=managed
          - --concurrency=2
